[package]
name = "git-locate"
version = "0.1.0"
edition = "2021"
authors = ["Alex Sayers <alex@asayers.com>"]
license = "Unlicense"
readme = "README.md"
repository = "https://github.com/asayers/git-locate"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
gix = "0.73.0"
nucleo = "0.5.0"
