[package]
name = "git-locate"
version = "0.1.0"
edition = "2021"
authors = ["Alex Sayers <alex@asayers.com>"]
license = "Unlicense"

[dependencies]
anyhow = "1.0.79"
crossterm = "0.27.0"
gix = "0.58.0"
nucleo = "0.3.0"
